// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CRN The CRN for this resource. Hello, testing swagger update script for 1Pipeline12345
//
// swagger:model CRN
type CRN string

// Validate validates this c r n
func (m CRN) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this c r n based on context it is used
func (m CRN) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
